# gvanno configuration options (TOML).

[other]
## Number of processes for vcfanno
n_vcfanno_proc = 4
## Number of forks for VEP
n_vep_forks = 4
## Ignore/skip intergenic variants
vep_skip_intergenic = false
## Predict loss-of-function variants using VEP's LofTee plugin
## Note that turning this on (true) is likely to increase VEP's run time substantially
lof_prediction = true
## VEP internal buffer size
## the number of variants that are read in to memory simultaneously 
buffer_size = 5000
## Customise the order of criteria used to pick the primary transcript in VEP (see https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_pick_order)
vep_pick_order = "canonical,appris,biotype,ccds,rank,tsl,length,mane"
